### ISSUE TITLE
This method needs an explicit return?

### ISSUE THREAD

**Issue by nishu** [draconiandev/sharescription#2]
https://github.com/draconiandev/sharescription/blob/eac8a8dcab90f3ec46c7221ba07de8347df569dd/app/models/share_record.rb#L44

**Comment by pavanprakash21** [comment]
No, it doesn't. All it does is, calls the #update action on the model with this particular attribute.
For ex:

```ruby
share_record = ShareRecord.first
share_record.shared? # => false
share_record.update(shared: true)
share_record.shared? # => true
```
is equivalent to

```ruby
share_record.shared? # => false
share_record.safe_toggle(:shared)
share_record.shared? # => true
```
also
```ruby
share_record.shared? # => true
share_record.safe_toggle(:shared)
share_record.shared? # => false
```

Since the parse won't fail as nothing else is being done on the object, I am not looking for an explicit return. The only place for a 500 possibility is to misspell `:shared`. That will be caught by specs.

I could have went ahead with #toggle since I am not catching any errors in the controller though.
